/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    EditorControls: typeof import('./src/components/EditorControls.vue')['default']
    IMdiBookmark: typeof import('~icons/mdi/bookmark')['default']
    IMdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    IMdiFileImageOutline: typeof import('~icons/mdi/file-image-outline')['default']
    IMdiFormatBold: typeof import('~icons/mdi/format-bold')['default']
    IMdiFormatHeader1: typeof import('~icons/mdi/format-header1')['default']
    IMdiFormatHeader2: typeof import('~icons/mdi/format-header2')['default']
    IMdiFormatHeader3: typeof import('~icons/mdi/format-header3')['default']
    IMdiFormatHeader4: typeof import('~icons/mdi/format-header4')['default']
    IMdiFormatHeader5: typeof import('~icons/mdi/format-header5')['default']
    IMdiFormatHeader6: typeof import('~icons/mdi/format-header6')['default']
    IMdiFormatItalic: typeof import('~icons/mdi/format-italic')['default']
    IMdiFormatQuoteOpen: typeof import('~icons/mdi/format-quote-open')['default']
    IMdiFormatStrikethroughVariant: typeof import('~icons/mdi/format-strikethrough-variant')['default']
    IMdiFormatSubscript: typeof import('~icons/mdi/format-subscript')['default']
    IMdiFormatSuperscript: typeof import('~icons/mdi/format-superscript')['default']
    IMdiFormatUnderline: typeof import('~icons/mdi/format-underline')['default']
    IMdiInformationVariantCircleOutline: typeof import('~icons/mdi/information-variant-circle-outline')['default']
    IMdiLinkVariant: typeof import('~icons/mdi/link-variant')['default']
    IMdiTableLarge: typeof import('~icons/mdi/table-large')['default']
    IMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    IMdiXml: typeof import('~icons/mdi/xml')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
  }
}
